Лабороторная работа №4
Programming-Classrooms/practicalworks-DashaDrozd pull request #3
Opened 2023-12-01 17:08 UTC by DashaDrozd

Вариант 3
В целочисленной квадратной матрице найти:
− максимальный элемент нижнего правого треугольника матрицы.
− переставить строки и столбцы матрицы так, чтобы в левом верхнем углу
матрицы оказался максимальный положительный элемент матрицы.

2023-12-01 17:26 UTC, Voio77 requested changes
Читай коменты.
Работаем, Дарья Юрьевна

2023-12-01 19:14 UTC, AlexandrOsiptsov requested changes
Внимательно просмотри комменты

2023-12-01 19:14 UTC, AlexandrOsiptsov commented on laboratory-task-4/lab4.cpp
> + }
Функции `maxInI(...)` и `maxInJ(...)` не зависят от итераторов `i` и `j`, следовательно, на каждой итерации вычисляют одно и то же значение. Вычислить можно один раз, сохранить в переменную, а потом использовать. 

Однако, здесь ты делаешь немного не то, что имелось ввиду.
- Для начала, тебе нужно написать 2 функции: swap заданных строк матрицы (можно сделать просто через указатели на эти строки), swap заданных столбцов матрицы (здесь уже нужно будет сделать один цикл). 
- Далее, тебе нужно написать функцию, определяющую индексы максимального элемента матрицы (прототип может выглядеть так: 
```cpp
void findMaxElemInds(
       int32_t** mtrx, 
       const size_t& mtrxSize,
       size_t& rowInd,
       size_t& colInd
     ) { ... }
```
- После того, как ты запишешь индексы максимального элемента, воспользуйся двумя предыдущими функциями, чтобы **сдвинуть** (а не просто поменять, т.е. относительный порядок остальных строк и столбцов должен сохраниться) строки и столбцы так, чтобы максимальный элемент оказался в нужном крае.

2023-12-01 19:14 UTC, AlexandrOsiptsov commented on laboratory-task-4/lab4.cpp
> + }
Плюсую

2023-12-27 22:23 UTC, AnnaSatolina requested changes
надо поработать

2023-12-27 22:23 UTC, AnnaSatolina commented on laboratory-task-4/main.cpp
> +    }
в функцию

2023-12-27 22:23 UTC, AnnaSatolina commented on laboratory-task-4/main.cpp
> +    int32_t** matrix;
начальная инициализация matrix?

2023-12-27 22:23 UTC, AnnaSatolina commented on laboratory-task-4/main.cpp
> +}
память не освободится

2023-12-27 22:23 UTC, AnnaSatolina commented on laboratory-task-4/main.cpp
> +            cout << std::setw(4) << matrix[i][j] << " ";
cout << std::setw(4) << matrix[i][j] << " ";
в это строке можно опустить << " "....не до конца поняла setw.

2023-12-27 22:23 UTC, AnnaSatolina commented on laboratory-task-4/main.cpp
> +    int32_t min, max;
это не максимум и минимум, правильно называй переменные.

2023-12-27 22:23 UTC, AnnaSatolina commented on laboratory-task-4/main.cpp
> +            if (i > size - 1 - j && matrix[i][j] > max) {
надо сразу брать то, что нужно

2023-12-27 22:23 UTC, AnnaSatolina commented on laboratory-task-4/main.cpp
> +            if (matrix[size-1-i][size-1-j] > max) {
нет пробелов ....    [size-1-i][size-1-j]
надо                       [ size - 1 - i][size - 1 - j]

2023-12-27 22:23 UTC, AnnaSatolina commented on laboratory-task-4/main.cpp
> +void movingMaxElementInLeftCorner(int32_t** matrix, const int32_t& size, size_t& rowInd, size_t& colInd)
функция выполняет перестановку, но не печать

2023-12-27 22:23 UTC, AnnaSatolina commented on laboratory-task-4/main.cpp
> +    }
функцией

2024-01-12 21:39 UTC, closed without merging

2024-06-17 16:19 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:26 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув