Лабораторная работа №3
Programming-Classrooms/practicalworks-DashaDrozd pull request #5
Opened 2023-12-03 18:32 UTC by DashaDrozd

### Условие лабраторной работы
Вариант 3
В массиве, состоящем из п целых элементов, вычислить:
- минимальный по модулю элемент массива;
- сумму элементов массива, расположенных после последнего нулевого элемента.
Преобразовать массив таким образом, чтобы в первой его половине располагались все
элементы с четными номерами , а во второй половине — с нечетными. Порядок следования
элементов не изменять.

2023-12-03 19:07 UTC, DashaDrozd commented
Исправляющий коммит: 1bc99cfa4a217bde0d9b9f8a92b7e2d2446e7aeb

2023-12-12 17:48 UTC, AnnaSatolina requested changes

2023-12-12 17:48 UTC, AnnaSatolina commented on laboratory-task-3/lab3.cpp
> +        std::cout << "CRINGE!!!!!" << std::endl;
неинформативно

2023-12-12 17:48 UTC, AnnaSatolina commented on laboratory-task-3/lab3.cpp
> +    int32_t arr[N];
почему статический? и где обработка тогда, что размер меньше 1000?

2023-12-12 17:48 UTC, AnnaSatolina commented on laboratory-task-3/lab3.cpp
> +    std:: cout<<"Sorted array: ";
объединить в одну

2023-12-12 17:48 UTC, AnnaSatolina commented on laboratory-task-3/lab3.cpp
> +    {
много раз повторяется 2*i

2023-12-27 22:11 UTC, AnnaSatolina requested changes
вообще все плохо со скобками, табуляцией и прочими моментами. Всё сама исправишь, слишком много отмечать всего

2024-06-17 16:19 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:26 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:40 UTC, merged