Лабораторная работа №2
Programming-Classrooms/practicalworks-DashaDrozd pull request #6
Opened 2023-12-03 20:41 UTC by DashaDrozd

### Условие лабраторной работы

3. добавляет слева и справа в записи числа цифру, повторяющуюся
максимальное число раз;

16. Для заданных натуральных чисел А и В определяет возможность
получения числа А вычеркиванием цифр из числа В.

19. Находит для заданного натурального N все пифагоровы тройки
чисел, каждое из которых не превосходит N.

2023-12-04 07:41 UTC, AlexandrOsiptsov commented on laboratory-task-2/lab2(19).cpp
> +#include <iostream>
+ все те же замечания

2023-12-04 07:41 UTC, AlexandrOsiptsov commented on laboratory-task-2/lab2(3).cpp
> +    std::cout <<max * pow(10,cnt) + num *10 + max<<'\n';
Любой бинарный оператор выделяется пробелами

2023-12-05 19:34 UTC, DashaDrozd commented
Исправляющий коммит:bb118e6fea2433952ae6d2e23d48226253235092

2023-12-27 22:08 UTC, AnnaSatolina requested changes
не клин код совсем......

2023-12-27 22:08 UTC, AnnaSatolina commented on laboratory-task-2/main1.cpp
> +           temp = num;
зачем два раза?

2023-12-27 22:08 UTC, AnnaSatolina commented on laboratory-task-2/main1.cpp
> +                    max = temp % 10;
вычисляем дважды temp % 10

2023-12-27 22:08 UTC, AnnaSatolina commented on laboratory-task-2/main2.cpp
> + int32_t inputNumber(int32_t& A)
разве А - константа?

2023-12-27 22:08 UTC, AnnaSatolina commented on laboratory-task-2/main2.cpp
> +int32_t devisionByNumb(int32_t& temp,int32_t& counterA)
скорее количество цифр!!!!! а не devisionByNumb
int32_t& counterA - это возвращаемое значение, зачем передавать его параметром?

2023-12-27 22:08 UTC, AnnaSatolina commented on laboratory-task-2/main2.cpp
> +    if (A > B) {
ещё функция?

2023-12-27 22:08 UTC, AnnaSatolina commented on laboratory-task-2/main2.cpp
> +        for (size_t j = 0; j < counterB; ++j) {
если использовала функции, то и надо было продолжить их использовать.

2024-06-17 16:57 UTC, AlexandrOsiptsov approved these changes

2024-06-17 16:57 UTC, merged