Лабороторная работа №5
Programming-Classrooms/practicalworks-DashaDrozd pull request #7
Opened 2023-12-06 18:01 UTC by DashaDrozd

#
### Условие лабраторной работы

Вычислить значение определенного интеграла с аналитически заданной подынтегральной
функцией с заданной точностью eps
А) по формуле левых прямоугольников;
Б) по формуле правых прямоугольников;
В) по формуле средних прямоугольников;
Г) по формуле трапеций;
Д) по формуле Симпсона (параболических трапеций).
Варианты Б,Г

![Снимок экрана от 2023-12-06 20-59-49](https://github.com/Programming-Classrooms/practicalworks-DashaDrozd/assets/146059236/f421ac8d-0c4a-4055-a30d-0157363998c5)

2023-12-07 10:17 UTC, AlexandrOsiptsov commented on laboratory-task-5/lab5.cpp
> +}
Названия лучше сделать с числами, а не словами. `func1`, `func2` ...

2023-12-07 10:17 UTC, AlexandrOsiptsov commented on laboratory-task-5/lab5.cpp
> +    double s2 = 0.5 * (f(a) + f(b)) * (b - a);
К чему отступ?

2023-12-07 10:19 UTC, AlexandrOsiptsov commented on laboratory-task-5/lab5.cpp
> +}
Не ясно, что значит `A` и `B`. Если это границы интегрирования, то так их и назови

2023-12-07 10:19 UTC, AlexandrOsiptsov commented on laboratory-task-5/lab5.cpp
> + b = 0;
Снова, названия

2023-12-07 10:19 UTC, AlexandrOsiptsov commented on laboratory-task-5/lab5.cpp
> + double (*funct[3])(double) = {functFirst,functSecond,functThird};
После запятой принято ставить пробел

2023-12-07 10:20 UTC, AlexandrOsiptsov commented on laboratory-task-5/lab5.cpp
> + }
Если происходит какая-то обработка ввода, то её лучше запереть в функцию, добавить вариативных аргументов

2023-12-07 10:21 UTC, AlexandrOsiptsov commented on laboratory-task-5/lab5.cpp
> +  cout << "Integrall of " << i + 1 << " function by trapecia method : " << trapIntegral(funct[i], a, b, eps) << '\n';
Интеграл - **"Intergtal"**

2023-12-07 10:22 UTC, AlexandrOsiptsov commented on laboratory-task-5/lab5.cpp
> +  cout << "Integrall of " << i + 1 << " function by trapecia method : " << trapIntegral(funct[i], a, b, eps) << '\n';
Трапеция - **"Trapezoid"**

2023-12-07 10:23 UTC, AlexandrOsiptsov commented on laboratory-task-5/lab5.cpp
> +double trapIntegral(const std::function<double(double)>& f, double a, double b,double eps )
**Trap** - Ловушка. Подумай над названием

2023-12-07 19:19 UTC, DashaDrozd commented
Исправляющий коммит:a577027dac01f54921dab40387d47435230a7934

2023-12-08 22:31 UTC, AlexandrOsiptsov requested changes
Всё круто. Функции, которые видела на скрине, где с Контуровым 66% match, стираешь и сама с нуля пишешь

2023-12-12 19:18 UTC, AnnaSatolina commented on laboratory-task-5/lab5.cpp
> +}
А я наоборот говорю, что лучше словами. Так даже в книжках написано. Поэтому она так и писала)

2023-12-27 21:59 UTC, AnnaSatolina approved these changes
пусть будет, но есть что исправить

2023-12-27 21:59 UTC, AnnaSatolina commented on laboratory-task-5/main.cpp
> +   while (fabs(s2 - s1) > eps) {
условие должн быть больше или равно

2023-12-27 21:59 UTC, AnnaSatolina commented on laboratory-task-5/main.cpp
> +   std::cin >> boarder2;
для каждого интеграла в условии уе есть границы. Надо было их ввести константами, например.

2024-01-10 11:21 UTC, AlexandrOsiptsov approved these changes

2024-01-11 08:20 UTC, merged