Лабораторная работа №7
Programming-Classrooms/practicalworks-DashaDrozd pull request #8
Opened 2023-12-12 16:28 UTC by DashaDrozd

### Условие лабраторной работы

3. Строка состоит из слов. Найти все слова-палиндромы и занести их в
новую строку в порядке возрастания их длин. Слова в новой строке должны
разделяться ровно одним пробелом.

2023-12-12 19:16 UTC, AnnaSatolina requested changes
Даша, ещё нужно поработать

2023-12-12 19:16 UTC, AnnaSatolina commented on laboratory-task-7/lab7.cpp
> +    for (size_t i = 0; i < length / 2; i++)
тогда уже length / 2 надо было занести в переменную!

2023-12-12 19:16 UTC, AnnaSatolina commented on laboratory-task-7/lab7.cpp
> +    findPalindromes(string, result);
нет сообщений о том, что палиндромов нет, нет проверки на пустоту строки. Где обработка исключений?

2023-12-12 19:16 UTC, AnnaSatolina commented on laboratory-task-7/lab7.cpp
> +    for (size_t i = 0; i < count - 1; i++)
count - 1 вычисляем каждую итерацию цикла

2023-12-12 19:16 UTC, AnnaSatolina commented on laboratory-task-7/lab7.cpp
> +int main() {
русские буквы не работают

2023-12-12 19:16 UTC, AnnaSatolina commented on laboratory-task-7/lab7.cpp
> +    char string[300];
почему 300?

2023-12-12 19:16 UTC, AnnaSatolina commented on laboratory-task-7/lab7.cpp
> +    char* palindromes[100];
почему 100?

2023-12-12 19:16 UTC, AnnaSatolina commented on laboratory-task-7/lab7.cpp
> +bool isFullString(char* string)
вообще не нравится эта функция

2024-01-06 18:54 UTC, AlexandrOsiptsov requested changes
Ты должна изменить старый файл, а не добавить новый

2024-06-17 16:55 UTC, AlexandrOsiptsov approved these changes

2024-06-17 16:56 UTC, merged